runtime: nodejs18
service: api

handlers:
  - url: /image/description
    static_dir: plantwise-ch2-ps530/image/description
    secure: always

  - url: /image/news
    static_dir: plantwise-ch2-ps530/image/news
    secure: always
  
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  BUCKET_NAME: "plantwise-ch2-ps530"
  PORT: 8080